### PR TITLE
metaverse-nft: not allow contract to call mint()

### PR DESCRIPTION
**Pull request by caffeinum**
_speculative._

https://www.reddit.com/r/ethdev/comments/8r6b93/is_txorigin_msgsender_a_secure_option_to_prevent/

TODO:
- [ ] estimate how many users minted using multisig
- [ ]

### CODE REVIEW

**Comment by theshadowagent** [comment]
Wow this is so good

**Comment by theshadowagent** [comment]
It will drop the multisig minting. Is this bad for communities?

**Comment by theshadowagent** [comment]
It might be actually better since it guarantees that the holders are actual people, e.g. "community members". I wonder if this should be an extra setting?

**Comment by caffeinum** [comment]
come back to this later, optionally include this as an extension

**Pull request closed without merging**
